export type PointType = 'warning' | 'info'

export interface KeyPoint {
  type: PointType
  text: string
}

export interface Phase {
  id: number
  title: string
  subtitle: string
  pages: string
  steps: string[]
  keyPoints: KeyPoint[]
}

export const phases: Phase[] = [
  {
    id: 1,
    title: 'Phase 1',
    subtitle: 'Configuration de base avec NAT/PAT et accès Internet',
    pages: '1–20',
    steps: [
      'Configurer les interfaces OUT (WAN), IN (LAN), DMZ sur le pare-feu SNS',
      'Définir le plan d\'adressage : OUT = 192.36.253.x/24, IN = 192.168.x.0/24, DMZ = 172.16.x.0/24',
      'Configurer la passerelle par défaut (192.36.253.1)',
      'Activer le proxy cache DNS',
      'Créer et activer la politique NAT "NAT Internet Pass all"',
      'Créer la règle de NAT dynamique (masquerading) sur l\'interface OUT',
      'Tester la connectivité Internet depuis un client',
    ],
    keyPoints: [
      { type: 'warning', text: 'L\'interface DMZ n\'est utilisée que pour héberger des serveurs — ne pas travailler dessus directement' },
      { type: 'warning', text: 'La passerelle par défaut doit pointer vers l\'IP du pare-feu SNS (192.36.253.1)' },
      { type: 'warning', text: 'Toujours sauvegarder la configuration avant de continuer' },
      { type: 'info', text: 'Chemin : Configuration > Réseau > Interfaces' },
      { type: 'info', text: 'Chemin : Configuration > Réseau > Routage > Routes statiques IPv4' },
      { type: 'info', text: 'Chemin : Configuration > Politique de sécurité > Filtrage et NAT' },
    ],
  },
  {
    id: 2,
    title: 'Phase 2',
    subtitle: 'Plan d\'adressage réseau et configuration des interfaces',
    pages: '21–29',
    steps: [
      'Sélectionner Configuration > Réseau > Interfaces',
      'Sortir du mode bridge par défaut et passer en mode routeur',
      'Configurer l\'interface IN avec IP fixe (192.168.x.1/24)',
      'Configurer l\'interface DMZ avec IP fixe (172.16.x.0/24)',
      'Configurer l\'interface OUT (192.36.253.x/24)',
      'Définir la passerelle par défaut : Configuration > Réseau > Routage > Routes statiques IPv4',
      'Créer l\'objet Machine "FWOUT_Siege" avec l\'IP 192.36.253.1',
    ],
    keyPoints: [
      { type: 'warning', text: 'En configuration usine, toutes les interfaces sont dans un bridge — il faut en sortir' },
      { type: 'warning', text: 'Si un message "Fondation" apparaît, déconnecter le câble réseau et changer l\'IP' },
      { type: 'warning', text: 'La lettre Y dans les noms d\'interfaces correspond à la lettre de votre agence' },
      { type: 'info', text: 'Chemin DNS cache proxy : Configuration > Réseau > Proxy cache DNS' },
      { type: 'info', text: 'Objet FWOUT_Siege : Configuration > Objets > Objets réseau > Ajouter > Machine' },
    ],
  },
  {
    id: 3,
    title: 'Phase 3',
    subtitle: 'Configuration des Objets Réseau (LAB 3)',
    pages: '30–37',
    steps: [
      'Créer les objets Machines pour chaque serveur de l\'agence (dns_priv, web_priv, ftp_priv, mail_priv)',
      'Créer les objets Machines pour les IPs publiques (dns_pub, web_pub, ftp_pub, mail_pub)',
      'Créer un groupe d\'objets "LAN_Y_Snpre" contenant les 4 serveurs internes',
      'Créer un objet Port TCP "webmail" sur le port 800',
      'Exporter la base d\'objets en CSV',
      'Importer des objets depuis un fichier CSV externe',
      'Comprendre les objets explicites vs pré-configurés',
    ],
    keyPoints: [
      { type: 'warning', text: 'Ne pas modifier les objets pré-configurés (FWOUT, Network_internals, Internet, etc.)' },
      { type: 'warning', text: 'Limiter les objets dynamiques (FQDN, Dynamic Host) — ils sollicitent le réseau' },
      { type: 'warning', text: 'Éviter les doublons lors de l\'import CSV — ils écrasent les objets existants' },
      { type: 'info', text: 'Chemin : Configuration > Objets > Objets réseau' },
      { type: 'info', text: 'Convention de nommage : srv_[service]_[priv/pub] (ex: srv_web_priv)' },
      { type: 'info', text: 'Le fichier CSV doit être encodé en UTF-8 pour éviter les erreurs d\'import' },
    ],
  },
  {
    id: 4,
    title: 'Phase 4',
    subtitle: 'Traduction d\'adresses (NAT/PAT)',
    pages: '38–42',
    steps: [
      'Activer la politique NAT "NAT Internet Pass all" existante',
      'Tester le NAT depuis un client (ping 192.36.253.1, naviguer sur Internet)',
      'Copier la politique "NAT Internet Pass all" et la renommer "Lab4_NAT"',
      'Désactiver la règle "Pass all" dans Lab4_NAT',
      'Créer la règle NAT dynamique (masquerading) : Network_internals > Firewall_out',
      'Créer les règles de redirection de ports pour FTP (srv_ftp_priv/pub)',
      'Créer les règles de redirection de ports pour Mail (srv_mail_priv/pub)',
      'Créer la règle de redirection pour le serveur Web (port 80 vers srv_web_priv)',
      'Activer le tracé sur la règle N°1 (NAT dynamique)',
      'Vérifier les logs dans Monitoring > LOGS > Journaux d\'audit > Trafic réseau',
    ],
    keyPoints: [
      { type: 'warning', text: 'Placer la règle de NAT dynamique EN DERNIÈRE POSITION dans la politique' },
      { type: 'warning', text: 'Dans "Destination originale", ne jamais laisser "Any" — sinon le SNS lui-même est natté' },
      { type: 'warning', text: 'Choisir l\'interface OUT comme "Interface de sortie" dans Configuration avancée' },
      { type: 'warning', text: 'Le NAT ne laisse jamais de trace dans les journaux de connexion — utiliser les journaux d\'audit' },
      { type: 'info', text: 'Chemin : Configuration > Politique de sécurité > Filtrage et NAT' },
      { type: 'info', text: 'Chemin logs : Monitoring > LOGS > Journaux d\'audit > Trafic réseau' },
    ],
  },
  {
    id: 5,
    title: 'Phase 5',
    subtitle: 'Filtrage protocolaire',
    pages: '43–48',
    steps: [
      'Copier la politique "Lab4_NAT" et la renommer "Lab5_Filtrage_NAT"',
      'Désactiver la règle "Pass all" dans la nouvelle politique',
      'Créer la règle ICMP sortante (réseau interne > Any, protocole ICMP Echo)',
      'Créer les règles d\'accès LAN vers DMZ (FTP, HTTP, SMTP)',
      'Créer la règle DNS interne (srv_dns_priv > FWOUT_Siege, port dns_udp)',
      'Créer les règles pour les trafics entrants (Internet > DMZ : Web, FTP, Mail)',
      'Créer les règles pour les réseaux distants (accès aux serveurs DMZ)',
      'Activer toutes les règles et activer la politique',
      'Tester les flux sortants depuis un client et les flux entrants',
    ],
    keyPoints: [
      { type: 'warning', text: 'L\'ordre des règles est crucial — la première règle qui correspond s\'applique' },
      { type: 'warning', text: 'La règle "Block all" implicite bloque tout ce qui n\'est pas explicitement autorisé' },
      { type: 'warning', text: 'Les pare-feux SNS utilisent la technologie SPI — les connexions établies sont suivies automatiquement' },
      { type: 'warning', text: 'Toujours ajouter un séparateur pour organiser les règles (Nouvelle règle > Séparateur)' },
      { type: 'info', text: 'Chemin : Configuration > Politique de sécurité > Filtrage et NAT > Filtrage' },
      { type: 'info', text: 'Règles implicites visibles : Configuration > Politique de sécurité > Règles implicites' },
    ],
  },
  {
    id: 6,
    title: 'Phase 6',
    subtitle: 'Filtrage applicatif (URL, SSL)',
    pages: '49–60',
    steps: [
      'Copier Lab5_Filtrage_NAT et renommer en "Lab6_URL_NAT"',
      'Créer une catégorie d\'URL personnalisée "black_list" avec badssl.com',
      'Créer une politique de filtrage URL "Lab6_URL_NAT" basée sur NAT Internet Pass all',
      'Ajouter les règles : résolution DNS, accès HTTP/HTTPS Internet',
      'Activer l\'inspection applicative sur la règle HTTP (Filtrage URL : Lab6_URL)',
      'Tester le blocage de badssl.com depuis un navigateur',
      'Configurer le proxy SSL (Configuration > Politique de sécurité > Filtrage SSL)',
      'Créer la catégorie "black_ssl_https" avec badssl.com',
      'Activer la règle "Déchiffrer" sur la politique Lab6_SSL',
      'Tester le blocage HTTPS de badssl.com',
    ],
    keyPoints: [
      { type: 'warning', text: 'Le filtrage URL ne fonctionne que sur le protocole HTTP — pas HTTPS (sauf avec proxy SSL)' },
      { type: 'warning', text: 'Le proxy SSL est positionné en "man in the middle" — il déchiffre et rechiffre le trafic' },
      { type: 'warning', text: 'La méthode "Filtrage SANS déchiffrement" utilise le SNI pour identifier le domaine' },
      { type: 'warning', text: 'Le déchiffrement SSL peut poser des problèmes légaux selon la réglementation (RGPD en France)' },
      { type: 'info', text: 'Chemin URL : Configuration > Objets > URL > Ajouter une catégorie personnalisée' },
      { type: 'info', text: 'Chemin SSL : Configuration > Politique de sécurité > Filtrage SSL' },
      { type: 'info', text: 'Vérifier l\'appartenance d\'un domaine : Configuration > Objets > Web angel Object > Classifier' },
    ],
  },
  {
    id: 7,
    title: 'Phase 7',
    subtitle: 'VPN SSL pour clients nomades',
    pages: '61–68',
    steps: [
      'Activer le portail captif pour la récupération des certificats client',
      'Configurer l\'annuaire interne LDAP : Configuration > Utilisateurs > configuration des annuaires',
      'Créer un utilisateur "vpn1" et un groupe "VPN"',
      'Attribuer les droits d\'accès VPN SSL au groupe',
      'Configurer le VPN SSL : Configuration > VPN > VPN SSL > ON',
      'Définir les réseaux : Net-SSLVPN_TCP (172.30.1.0/24) et Net-SSLVPN_UDP (172.31.1.0/24)',
      'Définir les réseaux accessibles : Network_internals',
      'Configurer les paramètres DNS du tunnel',
      'Activer le portail captif sur l\'interface externe',
      'Copier Lab6_URL_NAT et renommer en "Lab7_VPNSSL"',
      'Créer la règle de filtrage VPN SSL (Net-SSLVPN_TCP + UDP > Network_internals)',
      'Connecter le client OpenVPN depuis la machine cliente Linux ou Windows',
      'Vérifier la connexion dans Monitoring > Logs VPN',
    ],
    keyPoints: [
      { type: 'warning', text: 'Activer le portail captif uniquement sur l\'interface EXTERNE (pas LAN)' },
      { type: 'warning', text: 'Ne pas activer le portail captif sur l\'interface OUT — cela bloquerait tout le trafic' },
      { type: 'warning', text: 'Les logs VPN sont anonymes par défaut — passer en "LOGS ACCÈS COMPLET"' },
      { type: 'warning', text: 'Le client OpenVPN doit d\'abord télécharger le profil depuis le portail captif' },
      { type: 'info', text: 'Portail captif : https://[IP_OUT]/auth/admin' },
      { type: 'info', text: 'Chemin annuaire : Configuration > Utilisateurs > Configuration des annuaires > Créer LDAP Interne' },
      { type: 'info', text: 'Chemin logs VPN : Monitoring > Logs VPN' },
    ],
  },
  {
    id: 8,
    title: 'Phase 8',
    subtitle: 'VPN site-à-site IPSec',
    pages: '69–76',
    steps: [
      'Configurer le profil IKE Phase 1 : DH 14, durée 21600s, SHA-256, AES 256bits',
      'Configurer le profil IPSec Phase 2 : DH 14, durée 3600s, HMAC SHA-256, AES-GCM 256bits',
      'Définir le protocole par défaut en Phase 1 (Actions > Définir le protocole par défaut)',
      'Créer le tunnel IPSec site-à-site via l\'assistant',
      'Configurer le réseau local (Network_internals ou DMZ)',
      'Configurer le réseau distant (LAN de l\'agence correspondante)',
      'Renseigner la Passerelle distante (FW_B ou FW_A selon le sens)',
      'Choisir la clé prépartagée (PSK) : "Not1234"',
      'Lier les profils Phase 1 et Phase 2 au tunnel',
      'Activer la politique IPSec',
      'Créer la règle de filtrage pour le trafic VPN IPSec',
      'Vérifier dans Monitoring > VPN > VPN IPSec : Phase 1 et Phase 2 établies',
      'Tester la connectivité ping entre les deux agences',
    ],
    keyPoints: [
      { type: 'warning', text: 'Les deux pare-feux doivent avoir exactement les mêmes paramètres de chiffrement' },
      { type: 'warning', text: 'Firmware minimum requis : version 4.2.5' },
      { type: 'warning', text: 'La règle de filtrage IPSec doit autoriser le trafic via "Tunnel SSL : Lab7_VPNSSL"' },
      { type: 'warning', text: 'Vérifier que Phase 1 affiche "IKE SA established" et Phase 2 "IPSEC SA established"' },
      { type: 'info', text: 'Chemin chiffrement : Configuration > VPN > VPN IPSec > Profils de chiffrement' },
      { type: 'info', text: 'Chemin tunnel : Configuration > VPN > VPN IPSec > Politique de chiffrement-tunnels > Site à site' },
      { type: 'info', text: 'Monitoring : Monitoring > VPN > VPN IPSec' },
    ],
  },
]
